### ISSUE TITLE
Interpolate fields to faces when exporting plots/animations

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimateMachineCore.jl#49]
It's often very helpful to view plots on face fields, since they include the boundary points, and boundary conditions can be more easily verified.

**Comment by jakebolewski** [comment]
The plotting will respect the space the field is currently on so both centers and faces are plotted with bounds defined by the domain extent (in the vertical).  If the user wanted to interpolate it seems better to make this an explicit step.

**Comment by charleskawczynski** [comment]
Yeah, I guess we can add post-processing pieces elsewhere.
